name: Build and Publish

on:
  push:
    branches:
      - master
  # Schedule updates (each day)
  schedule:
    - cron: "0 8 * * *"  # every day at 8am UTC
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jre-version: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log-in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Publish
        run: |
          docker buildx build --push \
            --tag "ghcr.io/infrapack/jvm-slim:${{ matrix.jre-version }}" \
            --file "jre-${{ matrix.jre-version }}/Dockerfile" \
            --platform linux/amd64,linux/arm64 \
            "jre-${{ matrix.jre-version }}"